arm64: mm: Fix 'required_corepages' undeclared error when NUMA is enabled
The 'required_corepages' variable and its associated early_param handler
were incorrectly placed inside a #else block for #ifndef CONFIG_NUMA.
This caused build failures when CONFIG_NUMA was enabled because
arm64_memblock_init uses this variable regardless of the NUMA configuration.

Move these definitions to a global scope.

Fixes the following compilation error:
arch/arm64/mm/init.c:460:13: error: 'required_corepages' undeclared (first use in this function)
  460 |         if (required_corepages) {

Change-Id: I2e6244141f291eef8bdd3083af8faec1c95be44e
Signed-off-by: Josh Law <objecting@objecting.org>