arm64: ptrace/pointer_auth: Fix pointer auth build errors
Fix 'vabits_user undeclared' error by replacing it with VA_BITS, which is
used in this version of the kernel.

Also, remove the duplicated definition of the pac_mask_get function in
ptrace.c which caused a redefinition error.

Fixes the following compilation errors:
./arch/arm64/include/asm/pointer_auth.h:84:22: error: 'vabits_user' undeclared
   84 |         (GENMASK(54, vabits_user) | BIT(55))
      |                      ^~~~~~~~~~~

arch/arm64/kernel/ptrace.c:1000:12: error: redefinition of 'pac_mask_get'
 1000 | static int pac_mask_get(struct task_struct *target,

Change-Id: I4b5ec900617cd07260e5f8a406a73441928f1610
Signed-off-by: Josh Law <objecting@objecting.org>