debug-snapshot: Fix duplicate definition of dbg_snapshot_get_hardlockup
Remove the inline function definition of dbg_snapshot_get_hardlockup
which conflicts with the macro defined earlier in the file.

Fixes the following compilation error:
./include/linux/debug-snapshot.h:250:51: error: macro "dbg_snapshot_get_hardlockup" passed 1 arguments, but takes just 0
  250 | static inline int dbg_snapshot_get_hardlockup(void)
      |                                                   ^
./include/linux/debug-snapshot.h:222: note: macro "dbg_snapshot_get_hardlockup" defined here
  222 | #define dbg_snapshot_get_hardlockup()           do { } while(0)

Change-Id: I1b6ab52995f1e3a0ff4187576a6803c069e44523
Signed-off-by: Josh Law <objecting@objecting.org>